version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - database
  react-frontend:
    build:
      context: .
      dockerfile: react-frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
      POSTGRES_SSL: off
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
